name: Github Actions Demo

on:
  push:
    branches: 
      - main
  pull_request: 
    types:
      - opened


jobs:
    build-job:
      runs-on: ubuntu-latest
      steps:
        - run: echo "build app"
    
    test-job:
      runs-on: ubuntu-lastest
      needs: build-job
      steps:
        - run: echo "test job"
    
    deploy-job:
      runs-on: ubuntu-lastest
      needs: test-job
      steps:
        - run: echo "deploy job to server"

        